//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoUmbra.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_Public {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Public() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoUmbra.Resources.Strings.Public", typeof(Strings_Public).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto Umbra.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluación de contenido.
        /// </summary>
        internal static string EvaluationScreen_Title {
            get {
                return ResourceManager.GetString("EvaluationScreen.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de evaluaciones.
        /// </summary>
        internal static string MainScreen_HistoryTooltip {
            get {
                return ResourceManager.GetString("MainScreen.HistoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar evaluación.
        /// </summary>
        internal static string MainScreen_StartButton {
            get {
                return ResourceManager.GetString("MainScreen.StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema de moderación de contenido.
        /// </summary>
        internal static string MainScreen_Subtitle {
            get {
                return ResourceManager.GetString("MainScreen.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto Umbra.
        /// </summary>
        internal static string MainScreen_Title {
            get {
                return ResourceManager.GetString("MainScreen.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluar.
        /// </summary>
        internal static string Prompt_Button {
            get {
                return ResourceManager.GetString("Prompt.Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el texto a evaluar.
        /// </summary>
        internal static string Prompt_Label {
            get {
                return ResourceManager.GetString("Prompt.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado del análisis.
        /// </summary>
        internal static string Response_Label {
            get {
                return ResourceManager.GetString("Response.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluación completada..
        /// </summary>
        internal static string Status_Done {
            get {
                return ResourceManager.GetString("Status.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando contenido….
        /// </summary>
        internal static string Status_Evaluating {
            get {
                return ResourceManager.GetString("Status.Evaluating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparando análisis….
        /// </summary>
        internal static string Status_Waiting {
            get {
                return ResourceManager.GetString("Status.Waiting", resourceCulture);
            }
        }
    }
}
