<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Resources\Strings.Local.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.Local.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Strings.Public.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.Public.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings.Local.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Local.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings.Public.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Public.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
