<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\Cinzel\Cinzel-Black.ttf" />
    <None Remove="Resources\Fonts\Cinzel\Cinzel-Bold.ttf" />
    <None Remove="Resources\Fonts\Cinzel\Cinzel-ExtraBold.ttf" />
    <None Remove="Resources\Fonts\Cinzel\Cinzel-Medium.ttf" />
    <None Remove="Resources\Fonts\Cinzel\Cinzel-Regular.ttf" />
    <None Remove="Resources\Fonts\Cinzel\Cinzel-SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\Cinzel\Cinzel-Black.ttf" />
    <Resource Include="Resources\Fonts\Cinzel\Cinzel-Bold.ttf" />
    <Resource Include="Resources\Fonts\Cinzel\Cinzel-ExtraBold.ttf" />
    <Resource Include="Resources\Fonts\Cinzel\Cinzel-Medium.ttf" />
    <Resource Include="Resources\Fonts\Cinzel\Cinzel-Regular.ttf" />
    <Resource Include="Resources\Fonts\Cinzel\Cinzel-SemiBold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Strings.Local.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.Local.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Strings.Release.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.Release.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings.Local.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Local.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings.Release.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Release.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
